### ISSUE TITLE
Couple useful additions

### ISSUE THREAD

**Issue by Speiger** [Gaz492/TwitchAPI#3]
Hi. I have a couple additions that i would like to see.
I have a tool that keeps track of my mods. (Creating statistics)
But the issue is right now it uses the webpages to scan.
(I didn't know that this api exists and plan now to port over)
There is just a couple things that are missing that I need else I can not switch over.
(The tool is offline for now)

- Addons:
   - A list of addons so i can just browse. (Just a "List" of ProjectID/AddonIDs. So i dont have to download 50MB of data) Required should be a gameId & sectionId
   - A list of ModPacks that include that mod (Basically Including Dependendents on CF).
- ModPacks Versions:
   - A list of all Dependencies that the ModPack has.
   - MD5 of the File so downloads can be made properly
   - Download Count of that version
   - MultiAccess of ModPack Versions. So less api calls at once. (Like the Addons/Mods have)
- Mod Versions:
   - MD5 of the File so downloads can be made properly
   - Donwload Count of that version
   - MultiAccess of Mod Versions. So less api calls at once. (Like the Addons/Mods have)

(TL:DR basically most of the things that are visible on curse pages)

**Comment by SaphireLattice** [comment]
Looks like you are looking for those endpoints:
1. `https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId={categoryID}&gameId={gameId}&gameVersion={gameVersion}&index={index}&pageSize={pageSize}5&searchFilter={searchFilter}§ionId={sectionId}&sort={sort}`, everything except gameId is optional.
2. Modpack are handled very much like mods by the API. Just hit the `https://addons-ecs.forgesvc.net/api/v2/addon/{id}`, get needed info. You have to parse the `manifest.json` from the .ZIP file of modpack for most dependencies, though. Don't really see any MD5 checking? The checksum in JSON seems to be a MurmurHash2, see https://github.com/DaemonicLabs/Voodoo/blob/master/core/src/main/kotlin/voodoo/curse/MurmurHash2.kt. JSON endpoint does not seem to expose the downloads count, sadly. Not sure what MultiAccess is?
3. See above.

Most of this could be found in 5 minutes of looking at API. This repository is just a reference to the API, and is not affilated with CurseForge and thus cannot add anything to the API, it's just documenting what already exists.

Can anyone close this?

**Comment by comp500** [comment]
Just a note: 
- You can also POST a JSON array of ids to `https://addons-ecs.forgesvc.net/api/v2/addon` to request multiple at once
- See https://github.com/comp500/packwiz-installer/blob/master/src/main/java/link/infra/packwiz/installer/metadata/hash/Murmur2Hasher.java#L33 for a Murmur2 hashing implementation in Java

**Comment by Gaz492** [comment]
As was mentioned above this repo only serves to document the api that the twitch app uses, if there is anything missing feel free to either open an issue with the details of whats missing or submit a PR.

**Comment by Speiger** [comment]
@SaphireLattice I wish that this API provided everything I need.

> https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId={categoryID}&gameId={gameId}&gameVersion={gameVersion}&index={index}&pageSize={pageSize}5&searchFilter={searchFilter}§ionId={sectionId}&sort={sort}

Yeah remember when I asked not to download like 50 Megabytes of data just to get the projectIDs of all the Mods/ModPacks? This is exactly what I ment with what I don't want to use. Because Checking this info like frequently is not a good idea. 
Also after testing this method extensivly I found out that max provides 10.000 Mods. After that there is a "Not found Exception" provided. But I know for a fact that there is already +11000 mods on Curseforge. So this info is not even reylable because you can only see a certain amount of mods and not scan for "all of them" so I would have to make multiple scans just to ensure everything is displayed which isn't relyable because CF does not have a way properly filter everything.
And after a certain amount of time enough mods would have shown up that these do not cover everything.

>Modpack are handled very much like mods by the API. Just hit the https://addons-ecs.forgesvc.net/api/v2/addon/{id}, get needed info. You have to parse the manifest.json from the .ZIP file of modpack for most dependencies, though. Don't really see any MD5 checking? The checksum in JSON seems to be a MurmurHash2, see 

About the Hash. Ok I didn't know that it was that kind of info. So I can just convert this number to the MD5 good to know (if not then tell me) Here you can see where the MD5 is provided by curse itself:
https://www.curseforge.com/minecraft/mc-mods/jei/files/2757672

>See above. Except this time you get actual dependencies info, woohoo.

Yes that includes dependencies. That is true. But that only accounts for mods. Not modpacks. ModPack Dependencies list actually all the mods they use in "include" which after checking a normalpack through this API is not shown. Also "Dependent" which curse also provides is not provided here. Thats why I am asking for this kind of info so I don't want to make a "Clone" of curseforge itself to make actually everything work. (Which by the way because of not wanting to ddos curse I actually made a clone of most webpages just for testing most of the things, my harddrive is thanking me)

>Most of this could be found in 5 minutes of looking at API. This repository is just a reference to the API, and is not affilated with CurseForge and thus cannot add anything to the API, it's just documenting what already exists.

Yes 5 minutes would be enough to find this "Useless information" that I also found after 5 minutes. What I found after 2 days is that this API is lacking like 50-70% of the information.

> You can also POST a JSON array of ids to https://addons-ecs.forgesvc.net/api/v2/addon to request multiple at once

Yes that is true. But this only shows you mods not the mod versions. And the mod versions that are inside the mod is only "the suggested versions" not the actual list of versions that the mod has. Forestry has over 700 versions, so I would be forced to make 700 independent requests to see all the data. My request is: Please let me provide all the subVersions (that i know through the scanning) so I can get the actual info of them a lot easier. If you read my request then you would know that I actually mention the thing you said me to use.

> See https://github.com/comp500/packwiz-installer/blob/master/src/main/java/link/infra/packwiz/installer/metadata/hash/Murmur2Hasher.java#L33 for a Murmur2 hashing implementation in Java that works with CurseForge hashes

Yes I was not aware what that exactly was since the documentation did not state that. 
source= https://twitchappapi.docs.apiary.io/

>As was mentioned above this repo only serves to document the api that the twitch app uses, if there is anything missing feel free to either open an issue with the details of whats missing or submit a PR.

I wish I could provide a PR but honestly I have no idea how to add something like this properly.
my HTML knowledge is right now pretty limited and I am trying to catch up on that. But this stuff takes time to master. 
Thats why I made this "suggestions issue" but since it seems that this is not going to be added I will be forced to just open curseforge webpages to scan for the data. (Which is the most relyable source I found so far. (I was already using a wrapper third party tool before but that was unrelyable enough that I had to drop it))

It would be nice even if I sound like an asshole if you at least could read and doublecheck my requests properly. 
What I ask for is the data that I was not able to find. What I got (except for the Murmur thing) was "it already exists" with no proof behind it. 

@comp500 @Gaz492

**Comment by Speiger** [comment]
Here a testcase. Using Jsoup, FastUtil, Googles GsonLibrary
(FastUtil can be removed easily)
It is only there to fetch all the IDs to find out if there is new ones. Compared to CF thats 11-12 page API calls. while CF is like +500 webpages to open up.
```java
public static void main(String[] args)
{
	try
	{
		IntSet ids = new IntOpenHashSet();
		Connection c = Jsoup.connect("https://addons-ecs.forgesvc.net/api/v2/addon/search?gameId=432&sectionId=6").timeout(60000).ignoreContentType(true).maxBodySize(52428800);
		int lastSize = -1;
		int stepSize = 1000;
		while(true)
		{
			try
			{
				c.url("https://addons-ecs.forgesvc.net/api/v2/addon/search?gameId=432&pageSize="+stepSize+"&index="+ids.size()+"&sectionId=6");
				//Reusing the connection so that there isn't as many "new connection opening"
				JsonArray array = new JsonParser().parse(new BufferedReader(new InputStreamReader(c.execute().bodyStream()))).getAsJsonArray();
				for(JsonElement el : array)
				{
					ids.add(el.getAsJsonObject().get("id").getAsInt());
				}
				if(lastSize == ids.size())
				{
					//Since its a "set" duplicated IDs are removed. So stop when no new Ids are provided. If they have a fallback system)
					break; 
				}
				lastSize = ids.size();
				System.out.println(lastSize);
			}
			catch(Exception e)
			{
				if(stepSize == 1)
				{
					break;
				}
				stepSize /= 10;
			}
		}
		System.out.println("IDs: "+ids.size());
		JsonWriter writer = new JsonWriter(new OutputStreamWriter(System.out));
		writer.setIndent(" ");
		Streams.write(array, writer);
		writer.flush();
		while(true)
		{
			ThreadUtil.sleep(500); //Helper class that just allows me easier to call Thread.sleep(500);
		}
	}
	catch(Exception e)
	{
		e.printStackTrace();
	}
}
```

**Comment by Speiger** [comment]
To Provide more evidence:
Here is the dependencies that "You say is provided":
https://addons-ecs.forgesvc.net/api/v2/addon/250211/file/2520296
https://www.curseforge.com/minecraft/modpacks/a-minecrafters-odyssey/files/2520296

I hope you guys are able to see the difference.
These are offically dependencies according to Curseforge. Also these mods when you click on them (lets use JEI) can even see that this ModPack has them as a dependency
https://www.curseforge.com/minecraft/mc-mods/jei/relations/dependents

This information is really needed for me because I want to know how many modpacks still use my mods. But without this info I litterly need to make a clone (every day) of CurseForge to generate that data on my PC itself. Or I just make a couple hundred webpage calls download way less unesseary data and get the same result.

**Comment by Speiger** [comment]
> As was mentioned above this repo only serves to document the api that the twitch app uses, if there is anything missing feel free to either open an issue with the details of whats missing or submit a PR.

Ok since I am reading over this like for the 3rd time to make sure that I don't miss anything. You say open a Issue with what is missing or open a PR.

Just 1 question. just 1. What is this? What am I asking here to add to this api? Am I stupid? Is this not a: "Hey this data is missing so I don't need to access the webpages" issue? 

The more I read over this the more confused I get how you miss this "hey I need this extra data to use your API" issue. Which you stated I should provide. This feels like a Plothole in a really a book.

I should stop reconfirming everything so often. It makes the life a lot easier.

**Comment by Gaz492** [comment]
...
Ok going back the the original post.

> A list of addons so i can just browse. (Just a "List" of ProjectID/AddonIDs. So i dont have to download 50MB of data) Required should be a gameId & sectionId

You would need to use the search endpoint to go through everything. Using the `index` to define where the data starts

> A list of ModPacks that include that mod (Basically Including Dependendents on CF).

As far as i can tell this is not possible without downloading every modpack zip and looking through the manifest.json

> A list of all Dependencies that the ModPack has.

Again you would need to download the manifest from the modpack zips to get this i believe

> MD5 of the File so downloads can be made properly

Not possible twitch gives us murmur hashes `fingerprints`

> Download Count of that version

Unless im missing something then not possible

> MultiAccess of ModPack Versions. So less api calls at once. (Like the Addons/Mods have)

See docs regarding getting multiple addons

> MD5 of the File so downloads can be made properly

Not possible twitch gives us murmur hashes `fingerprints`

> Download Count of that version

Unless im missing something then not possible

> MultiAccess of Mod Versions. So less api calls at once. (Like the Addons/Mods have)

See docs regarding getting multiple addons

Regarding wanting more proof download postman and give the api endpoints a try

**Comment by Speiger** [comment]
Ok I am answering this point by point and then I am just adding my final thoughts.

>You would need to use the search endpoint to go through everything. Using the index to define where the data starts

Already did that and stated its not relyable at all. Stops after 10000 and even trying to go further does not work. Also 50 MB of JsonData where I only need like 1% of that. (Again maybe a couple light weight functions?)

>As far as i can tell this is not possible without downloading every modpack zip and looking through the manifest.json

Wait don't you have access to CF server data? Even if not. Why not load up the versions once since the dependencies should be somewhat final. Per version. (In other words load up the webpages)

> Again you would need to download the manifest from the modpack zips to get this i believe

Same answer as the one above.

>Unless im missing something then not possible

Eh it should be listed in the CF data because even CF shows that data live. It updates the moment downloads got added for the daily usage of users.

>See docs regarding getting multiple addons

You still get me wrong. I mean not "Multiple AddonIDS/ProjectIDs", I mean a "JsonObject with a "projectID" and a JsonArray with the "FileIDs/ReleaseIDs". Because 1 Adddon can have 500 releases. I want to scan all the releases at once which the API does not provide.
TL:DR: Reading 1 Addon but over 500 files. Because there is 11k mods, but over 110k modVersions.

>Not possible twitch gives us murmur hashes fingerprints

Yeah its possible. If twitch does not provide you the data. Get it of their Offical Sites. Yes its more overhead but you ask for a simple "string" not a the entire database. They already give you a lot data in the first place.

>Regarding wanting more proof download postman and give the api endpoints a try

Already used the API a lot tried to implement it into my system. Failed because basic information that is cached by Twitch/CurseForge is there but not provided by you which may or may not be your fault I don't know, Honestly.
But If you want to catch all the Requests (for the bigger data collectors) you should maybe ask your contact that they provide at least all the information thats visible to the public.
Because we both know that curse has a lot of data about these things. And may or may not have soon quite a lot more outside access.
https://www.curseforge.com/minecraft/mc-mods/jei/files/2757672 (Just to proof my point that cf has the data)

What interests me right now the most because is: Where do you get your data from?

Thanks @Gaz492 for providing me with this kind of info. It helped a lot. (Even if you can not see what it helped with)

**Comment by Speiger** [comment]
Just now

**Comment by Speiger** [comment]
I though he was the guy who managed the api, because there was no indicator to state overwise.

**Comment by Speiger** [comment]
And this at the documentation is not really but also missleading in that point. Since people "Like me" could think: Hey if something is missing in the API it could also mean that you can ask here for more additions.
![picture](https://user-images.githubusercontent.com/2556269/63767562-4fd9c200-c8ce-11e9-95f4-92e5ed339f7f.png)

I mean yes its the api documentation but on othe other hand nothing states: This is if you want changes for the documentation and not actual changes to the what the API provides.

**Comment by comp500** [comment]
SaphireLattice's reply stated this clearly:
"This repository is just a reference to the API, and is not affilated with CurseForge and thus cannot add anything to the API, it's just documenting what already exists."

**Comment by comp500** [comment]
The Get Addon Files endpoint should also provide most of the mod files, I'm not sure if there's a limit on the number of files it provides.

**Comment by Speiger** [comment]
Yes I know.
But if there is no other source of relyable data provided there is no choice.

**Comment by modmuss50** [comment]
🍿

**Comment by Speiger** [comment]
well at least we established that the api is worth shit when it comes to seriouse usage. I think at least that is stated.
Since this turns now into a troll fest. I think its no longer worth the conversation.

**Comment by Gaz492** [comment]
Seeing as i dont own the api then i dont care if its shit, I just provied some documentation for it
