### ISSUE TITLE
Getting 404

### ISSUE THREAD

**Issue by GameBurrow** [Gaz492/TwitchAPI#5]
I've been trying to use this API to make an automated server builder using our clients .json file, however `Get Addon File Information` gets 404 when using Java or Postman or when I try the API console on your documentation.
```
Response
We encountered an error. Please try later.
```

Accessing the API through browser works interestingly.

**Comment by Gaz492** [comment]
I cant seem to replicate this whats the addon id and file id you are using?
![Postman_2019-10-06_14-23-46](https://user-images.githubusercontent.com/840990/66269807-f8bbfb00-e844-11e9-9b17-9afc4e0f7e6b.png)

**Comment by GameBurrow** [comment]
Whatever issue it was (today morning and yesterday), it's now gone. Sorry about that.
