### ISSUE TITLE
Searching for Bukkit Plugins

### ISSUE THREAD

**Issue by ArnyminerZ** [Gaz492/TwitchAPI#7]
Hi, I am really confused using this API, but I am trying to get along.
I'm trying to search for some bukkit plugins, for downloading them. I've found that the Bukkit Plugin category id is `5` (https://addons-ecs.forgesvc.net/api/v2/category/5), and searching for the section id, I found this list: https://addons-ecs.forgesvc.net/api/v2/category/section/5, where the 5, I suppose is the category.
Searching for "Developer Tools", for example (id 122), I made up this url: https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=5&gameId=432&gameVersion=1.15&index=0&pageSize=25&searchFilter=vault&sectionId=122&sort=0. 432 is for Minecraft, at 1.15, searching for Vault, the first result at the official website: https://www.curseforge.com/minecraft/bukkit-plugins/developer-tools?filter-game-version=2020709689%3A7667&filter-sort=4.
But I just keep getting empty arrays.

Any help, pls?

**Comment by comp500** [comment]
I'm not sure if Bukkit plugins even show up in the API, because you can't install them in the Twitch launcher.

**Comment by ArnyminerZ** [comment]
Oh... I see the point... So I won't be able to use this API for my app... Thanks any way.
